secrets:
  DB_PASSWORD:
    file: ./secrets/db_password.txt
  SECRET_JWT:
    file: ./secrets/secret_jwt.txt
  PEPPER:
    file: ./secrets/pepper.txt

services:
  service-viagens:
    build: ./service-viagens
    ports:
      - '3001:3001' #Por enquanto vai ter acesso público pra teste, e pq n temos o API Gateway pronto.
    depends_on:
      - db-viagens
    volumes:
      - ./service-viagens:/usr/src/app # Meu código = Código no container
      - /usr/src/app/node_modules # node_modules do container != meu node_modules
    env_file:
      - ./service-viagens/.env
    secrets:
      - DB_PASSWORD

  db-viagens:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: viagens_db
      POSTGRES_USER: usuario     
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    volumes:
      - db-viagens-data:/var/lib/postgresql/data
    secrets:
      - DB_PASSWORD

  service-usuario:
    build: ./service-usuario
    ports:
      - '3000:3000' # Por enquanto vai ter acesso público pra teste, e pq n temos o API Gateway pronto.
    depends_on:
      - db-usuario
    volumes:
      - ./service-usuario:/usr/src/app # Meu código = Código no container
      - /usr/src/app/node_modules # node_modules do container != meu node_modules
    env_file:
      - ./service-usuario/.env
    secrets:
      - DB_PASSWORD
      - SECRET_JWT
      - PEPPER

  db-usuario:
    image: postgres:15
    environment:
      POSTGRES_DB: banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - DB_PASSWORD

  service-grupos:
    build: ./service-grupos
    ports:
      - '3002:3002' #Por enquanto vai ter acesso público pra teste, e pq n temos o API Gateway pronto.
    depends_on:
      - db-grupos
      - rabbitmq
    volumes:
      - ./service-grupos:/usr/src/app # Meu código = Código no container
      - /usr/src/app/node_modules # node_modules do container != meu node_modules
    env_file:
      - ./service-grupos/.env
    secrets:
      - DB_PASSWORD
      - SECRET_JWT

  db-grupos:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: grupos_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    volumes:
      - db-grupos-data:/var/lib/postgresql/data
    secrets:
      - DB_PASSWORD

  service-despesas:
    build: ./service-despesas
    ports:
      - '3003:3003' #Por enquanto vai ter acesso público pra teste, e pq n temos o API Gateway pronto.
    depends_on:
      - db-despesas
      - rabbitmq
      - redis
    volumes:
      - ./service-despesas:/usr/src/app # Meu código = Código no container
      - /usr/src/app/node_modules # node_modules do container != meu node_modules
    env_file:
      - ./service-despesas/.env
    secrets:
      - DB_PASSWORD

  db-despesas:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: despesas_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    volumes:
      - db-despesas-data:/var/lib/postgresql/data
      - ./service-despesas/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - DB_PASSWORD

  service-orquestrador:
    build: ./service-orquestrador
    ports:
      - '3004:3004' #Por enquanto vai ter acesso público pra teste, e pq n temos o API Gateway pronto.
    depends_on:
      - db-orquestrador
      - rabbitmq
    volumes:
      - ./service-orquestrador:/usr/src/app # Meu código = Código no container
      - /usr/src/app/node_modules # node_modules do container != meu node_modules
    env_file:
      - ./service-orquestrador/.env
    secrets:
      - DB_PASSWORD

  db-orquestrador:
    image: postgres:15
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: orquestrador_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    volumes:
      - db-orquestrador-data:/var/lib/postgresql/data
      - ./service-orquestrador/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - DB_PASSWORD

  pgadmin:
    # Para poder editar os bancos - demora pra inicializar
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-devops
    ports:
      - "5672:5672" # Porta padrão para os microsserviços conectarem
      - "15672:15672" # Painel visual do RabbitMQ (acesse http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: redis-devops
    ports:
      - "6379:6379" # Cache do service-despesas (taxas de câmbio, dashboard)

volumes:
  db-data:
  db-viagens-data:
  db-grupos-data:
  db-despesas-data:
  db-orquestrador-data: